/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundWrapper: typeof import('./components/service/BackgroundWrapper.vue')['default']
    BoundingBox: typeof import('./components/service/BoundingBox.vue')['default']
    CircleStencil: typeof import('./components/stencils/CircleStencil.vue')['default']
    Cropper: typeof import('./components/Cropper.vue')['default']
    DraggableArea: typeof import('./components/service/DraggableArea.vue')['default']
    DraggableElement: typeof import('./components/service/DraggableElement.vue')['default']
    HandlerWrapper: typeof import('./components/service/HandlerWrapper.vue')['default']
    LineWrapper: typeof import('./components/service/LineWrapper.vue')['default']
    Preview: typeof import('./components/helpers/Preview.vue')['default']
    PreviewResult: typeof import('./components/service/PreviewResult.vue')['default']
    RectangleStencil: typeof import('./components/stencils/RectangleStencil.vue')['default']
    SimpleHandler: typeof import('./components/handlers/SimpleHandler.vue')['default']
    SimpleLine: typeof import('./components/lines/SimpleLine.vue')['default']
    StencilPreview: typeof import('./components/service/StencilPreview.vue')['default']
    TransformableImage: typeof import('./components/service/TransformableImage.vue')['default']
  }
}
